### ISSUE TITLE
/ayoseun/geth-lte/  Private repository?

### ISSUE THREAD

**Issue by Exarcun** [goethercore/goether#33]
Trying to setup the project i get this issue:

go get github.com/goethercore/goether

go: github.com/ayoseun/geth-lte@v1.2.4: reading github.com/ayoseun/geth-lte/go.mod at revision v1.2.4: git ls-remote -q origin in /home/ziion/go/pkg/mod/cache/vcs/069168b74c9ef74dab17d62166790172b205660f41c392f08247c7e41a197862: exit status 128:

Also tried to git clone /goether but I cannot access the functionalities I need

**Comment by Ayoseun** [comment]
Hi there, geth-lte has been discontinued in favour of goether, i suppose this should work https://github.com/goethercore/goether.git
